name: amaescola
description: A Flutter project for school attendance.

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  postgres: ^2.4.0 # Dependência para PostgreSQL

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
